/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  safelist: [
        'fill-laranja',
        'fill-azul-claro',
        'fill-roxo',
        'fill-rosa',
        'fill-vermelho',
        'fill-verde',
        'fill-amarelo',
        'fill-marrom',
        'bg-laranja',
        'bg-azul-claro',
        'bg-roxo',
        'bg-rosa',
        'bg-vermelho',
        'bg-verde',
        'bg-amarelo',
        'bg-marrom',
        'text-laranja',
        'text-azul-claro',
        'text-roxo',
        'text-rosa',
        'text-vermelho',
        'text-verde',
        'text-amarelo',
        'text-marrom',
        'border-laranja',
        'border-azul-claro',
        'border-roxo',
        'border-rosa',
        'border-vermelho',
        'border-verde',
        'border-amarelo',
        'border-marrom',
    ]
}

