export type NomeEspaco =
    // Propriedades
    | 'Av. Sumaré'
    | 'Av. Presidente Vargas'
    | 'Rua 25 de Março'
    | 'Av. São João'
    | 'Av. Paulista'
    | 'Av. Veneza'
    | 'Niterói'
    | 'Av. Atlântica'
    | 'Av. Ipiranga'
    | 'Boulevard Higienópolis'
    | 'Av. Presidente Kubitschek'
    | 'Ipanema'
    | 'Leblon'
    | 'Copacabana'
    | 'Av. Cidade Jardim'
    | 'Pacaembu'
    | 'Ibirapuera'
    | 'Barra da Tijuca'
    | 'Jardim Botânico'
    | 'Lagoa Rodrigo de Freitas'
    | 'Av. Morumbi'
    | 'Rua Oscar Freire'
    // Estação de metrô
    | 'Estação do Maracanã'
    | 'Estação do Méier'
    | 'Estação de Conexão'
    | 'Estação da República'
    // Companhia
    | 'Companhia Elétrica'
    | 'Companhia de Saneamento Básico'
    // Outros espaços
    | 'Cofre'
    | 'Sorte'
    | 'Imposto de Renda'
    | 'Taxa de Riqueza'
    | 'Ponto de Partida'
    | 'Prisão'
    | 'Estacionamento'
    | 'Vá para Prisão'
